### ISSUE TITLE
Javascript based on window size

### ISSUE THREAD

**Issue by gastaldi** [forge/website-design#40]
This is more of a question than an issue itself: I noticed that `forge.jquery.js` contains some JavaScript in charge of resizing elements depending on the window size (https://github.com/forge/website-design/blob/master/js/forge.jquery.js#L59-L185). 

Is it possible to abstract those as CSS rules? I am coding your design using AngularJS (as a single page app) and I am afraid that those functions may not work when the content is dynamically replaced (given that they are called only once and not on every page change).

**Comment by visuale** [comment]
I could give it another shot, but most of the .resize() functions were for specific elements that were ignoring the height & margin rules. For instance, a section like the "Works In the Environment You Use" part of the main page was problematic as CSS because the text and buttons kept overlapping, and sliding out of view with just CSS.

For something like that, if you think it'll look okay to have fixed height/width settings for all the elements, then I can set that way but that means that at certain screen widths, the content is going to look rather spaced-apart and probably less vertically-aligned.

**Comment by gastaldi** [comment]
I don't see any problem in recalculating it on resize. I think it's better leave as it is for the time being.
